### ISSUE TITLE
the xAxis on chartBaseView missed after reload for times 

### ISSUE THREAD

**Issue by 13298897828** [i-schuetz/SwiftCharts#243] opened 2017-03-29 12:02 UTC
I use the chart and change the data use two button ,but i find the Layer on the chartBaseView missed after tap for times ,I don't know how could happened , 
once I change the data  i remove the chart.view 
 use 

      self.chart?.view.removeFromSuperview()

 to remove it .
and  then  make a new one 

    let chart = Chart(
                frame: chartFrame,
                layers: [
                  xAxis,
                  touchLayer,
                  chartPointsLayer1,
                  showCoordsLinesLayer,
                  chartPointsLineLayer,
                  chartPointsCircleLayer1,
                  ]
           )
     self.chart = chart  
 
What should I do with it ?

**Comment by i-schuetz** [comment] 2017-03-29 20:11
Hi. If you remove the view you of course have to add it again. Alternatively if you are using autolayout you just have to pass the view to the chart, instead of frame, and to update it 
```
for view in chart.view.subviews {
    view.removeFromSuperview()
}
initChart() // code to create chart instance
chart.view.setNeedsDisplay() // this may be necessary to trigger a redraw
```

If you continue experiencing problems, please upload an example to your github where I can reproduce the problem and I'm happy to help.

**Comment by 13298897828** [comment] 2017-04-05 06:37
Hi,I'm so sorry to waste you so much time ,but I add the code it didn't work for me ,and I write a demo about my question, Hope you can find what's error I made ,Thanks 
(I test it and it happend On iPhone 7 plus/iPhone 6s plus / iPhone 6 plus,just tap the button "2016 / 2017" for times)
[demo link]( https://github.com/13298897828/chartsDemo)

**Comment by 13298897828** [comment] 2017-04-10 02:15
hi,did you see the demo I submit......................

**Comment by i-schuetz** [comment] 2017-04-11 20:38
Hey. I did indeed miss your message. Sorry!

I can't reproduce it though. Tested with the simulator and an iPhone 6. Clicked many times quickly on 2016/2017 and didn't see anything abnormal. Except that when switching the chart doesn't preserve the current scroll position but resets to a fixed one, but that doesn't seem to what you're talking about.

**Comment by 13298897828** [comment] 2017-04-13 02:54
I test it on my iphone 6s ,and it worked well too,but iphone 6 plus/ iphone 7 it's really missed ,and I just take the picture 

and  I try to find the layers  on chartsBaseView, but there is nothing.
![missinglayer](https://cloud.githubusercontent.com/assets/9361798/24946207/b96996c2-1f94-11e7-8e6a-2f6e9fd08c97.png)

**Comment by 13298897828** [comment] 2017-04-13 08:55
![Uploading ShotScreen.png…]()
![Uploading ShotScreen副本.jpg…]()

**Comment by 13298897828** [comment] 2017-04-13 09:14
![shotscreen](https://cloud.githubusercontent.com/assets/9361798/24998421/a5892f54-206c-11e7-90bd-4dea6e92cbc6.png)

**Comment by i-schuetz** [comment] 2017-04-13 18:26
Hmm. Still can't reproduce it. The screens you're posting are not from your demo project. Are you sure that this problem can be reproduced with the demo project / the reason is not only in your actual project?

Btw, for panning, you can use master, it has better support for this.

**Comment by 13298897828** [comment] 2017-04-15 02:56
well,before I upload the demo, I had test  it ,and it can repeat,just need a iphone 7 plus / iphone 6s plus / iphone 6 plus,  I don't know why .. it just happend 5.5 inch screen.

**Comment by i-schuetz** [comment] 2017-04-17 21:03
As I said, you will have to help debugging this, I can't reproduce and don't have an iPhone 7+ or iPhone 6s at hand. The only thing that could be special about these devices though is the iOS version, because if it was the screen size I would be able to reproduce it with the simulator. I can't.

Happy to assist further, especially if this leads to a bug fix, but you'll have to help a little with the debugging.

**Closed** 2017-07-26 19:18 UTC
Labels: ?, waiting for user
